name: free42
base: core18 # the base snap is the execution environment for this snap
version: "v3.0.6" # just for humans, typically '1.2+git' or '1.3.2'
summary: An HP-42S Calculator Simulator
description: |
  Free42 is a re-implementation of the HP-42S Scientific Programmable Calculator
  and HP-82240 Printer.  It is a complete rewrite, not using any HP code. It does
  not require an HP-42S ROM image.  Even though it contains significant
  enhancements compared to the original calculator, Free42 remains fully
  compatible with the HP-42S, both in its user interface and in its ability to run
  programs written for the HP-42S.

architectures:
  - build-on: i386
  - build-on: amd64

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  free42:
    command: free42dec
    extensions: [gnome-3-28]
    #plugs: [unity7, home, pulseaudio]
    plugs: [home]

parts:
  free42:
    plugin: make
    source: https://github.com/thomasokken/free42.git
    source-tag: v3.0.6
    override-build: |
      ./build-gtk
      ls packages
      tar xvfz packages/*.tgz
      ls Free42Linux
      cp Free42Linux/* $SNAPCRAFT_PART_INSTALL
      ls $SNAPCRAFT_PART_INSTALL
